services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env.mc
    ports:
      - "${SERVER_PORT}:25565"
    volumes:
      - ./world:/data/world
      - ./logs:/data/logs
      - ./mods:/data/mods
      - ./server.properties:/data/server.properties
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: ${MEMORY_LIMIT}
        reservations:
          cpus: '${CPU_RESERVATION}'
          memory: ${MEMORY_RESERVATION}