services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env.mc
    ports:
      - "${SERVER_PORT}:25565"
    volumes:
      - ./world:/data/world
      - ./logs:/data/logs
      - ./mods:/data/mods
      - ./server.properties:/data/server.properties
      - ./config:/data/config
      - /dev/hugepages:/dev/hugepages
      - ${PLAYER_MGMT_PATH}/banned-ips.json:/data/banned-ips.json
      - ${PLAYER_MGMT_PATH}/banned-players.json:/data/banned-players.json
      - ${PLAYER_MGMT_PATH}/ops.json:/data/ops.json
      - ${PLAYER_MGMT_PATH}/usercache.json:/data/usercache.json
      - ${PLAYER_MGMT_PATH}/whitelist.json:/data/whitelist.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: ${MEMORY_LIMIT}
        reservations:
          cpus: '${CPU_RESERVATION}'
          memory: ${MEMORY_RESERVATION}