services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: ${TYPE}
      VERSION: ${MINECRAFT_VERSION}
      NEOFORGE_VERSION: beta
      MEMORY: ${MEMORY}
    ports:
      - "${SERVER_PORT}:25565"
    volumes:
      # HDD Mount
      - ${MINECRAFT_DATA_PATH}/mods:/data/mods
      - ${MINECRAFT_DATA_PATH}/world:/data/world
      - ${MINECRAFT_DATA_PATH}/config:/data/config
      - ${MINECRAFT_DATA_PATH}/backups:/backups
      - ${MINECRAFT_DATA_PATH}/logs:/data/logs
      # SSD Mount
      - ./server.properties:/data/server.properties
      - ./whitelist.json:/data/whitelist.json
      - ./ops.json:/data/ops.json
      - ./banned-players.json:/data/banned-players.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: ${MEMORY_LIMIT}
        reservations:
          cpus: '${CPU_RESERVATION}'
          memory: ${MEMORY_RESERVATION}