services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env.docker
    environment:
      EULA: true
      TYPE: ${TYPE}
      VERSION: ${MINECRAFT_VERSION}
      NEOFORGE_VERSION: beta
      MEMORY: ${MEMORY}
    ports:
      - "${SERVER_PORT}:25565"
    volumes:
      - ./world:/data/world
      - ./backups:/backups
      - ./logs:/data/logs
      - ./mods:/data/mods
      - ./config:/data/config
      - ./server.properties:/data/server.properties
      - .mc-admin/whitelist.json:/data/whitelist.json
      - .mc-admin/ops.json:/data/ops.json
      - .mc-admin/banned-players.json:/data/banned-players.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: ${MEMORY_LIMIT}
        reservations:
          cpus: '${CPU_RESERVATION}'
          memory: ${MEMORY_RESERVATION}